crawler:
  concurrent_requests: 5
  requests_per_second: 10
  max_retries: 3
  request_timeout: 30.0
  follow_redirects: true
  verify_ssl: true
  max_depth: 5

processing:
  allowed_tags:
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6
    - p
    - a
    - code
    - pre
    - blockquote
    - ul
    - ol
    - li
    - table
    - thead
    - tbody
    - tr
    - th
    - td
    - img
    - em
    - strong
    - br
    - hr
    - div
    - span
  preserve_whitespace_elements:
    - pre
    - code
  code_languages:
    - python
    - javascript
    - typescript
    - java
    - cpp
    - csharp
    - go
    - rust
    - php
    - ruby
    - swift
    - kotlin
    - scala
    - html
    - css
    - sql
  max_heading_level: 6
  max_content_length: 1000000
  min_content_length: 50

quality:
  min_content_length: 100
  max_content_length: 100000
  min_headings: 1
  max_heading_depth: 6
  min_internal_links: 1
  max_broken_links_ratio: 0.1
  required_metadata_fields:
    - title
    - description
    - keywords
  allowed_heading_skips: 1
  min_readability_score: 60.0
  max_duplicate_content_ratio: 0.2

organization:
  min_similarity_score: 0.3
  max_versions_to_keep: 10
  index_chunk_size: 1000
  category_rules:
    api:
      - api
      - endpoint
      - rest
      - graphql
    guide:
      - guide
      - tutorial
      - how-to
      - howto
    reference:
      - reference
      - doc
      - documentation
    example:
      - example
      - sample
      - demo
    concept:
      - concept
      - overview
      - introduction
  stop_words:
    - a
    - an
    - and
    - are
    - as
    - at
    - be
    - by
    - for
    - from
    - has
    - he
    - in
    - is
    - it
    - its
    - of
    - on
    - that
    - the
    - to
    - was
    - were
    - will
    - with

crawl4ai:
  max_retries: 3
  timeout: 30.0
  headers:
    User-Agent: "Crawl4AI/1.0 Documentation Crawler"
  follow_redirects: true
  verify_ssl: true
  max_depth: 5

lightpanda:
  executable_path: "lightpanda"
  host: "127.0.0.1"
  port: 9222
  timeout: 30.0
  max_retries: 3
  wait_for_load: true
  wait_time: 2.0
  javascript_enabled: true
  user_agent: "Lib2DocScrape/1.0 (Lightpanda) Documentation Crawler"
  viewport_width: 1280
  viewport_height: 800
  extra_args: []

library_tracking:
  registry_file: "library_registry.json"
  max_versions_to_keep: 10
  auto_detect_versions: true
  version_pattern: "v?(\\d+\\.\\d+\\.\\d+)"

benchmarking:
  output_dir: "benchmark_results"
  generate_charts: true
  metrics:
    - crawl_time
    - content_size
    - memory_usage
    - success_rate
  timeout: 60.0

logging:
  level: "INFO"
  file: "lib2docscrape.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
